spring.application.name=usuario

server.port=8081
#Uso de postgres sistema Operacional
#spring.datasource.url=jdbc:postgresql://localhost:5432/microservice-usuario
#Uso do Postgres Docker
spring.datasource.url=jdbc:postgresql://db:5432/microservice-usuario
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update

#Adiconar Endereço e nome da fila abaixo
spring.rabbitmq.addresses= # endereço da fila
broker.queue.email.name=# nome da fila

management.endpoints.web.exposure.include=health,metrics,swagger-ui
management.endpoint.health.show-details = always

management.metrics.enable.all=true

springdoc.show-actuator=true